%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: ${displayName}
file_extensions:
  - Dockerfile
scope: source.shell, source.dockerfile
contexts:
  main:
    - match: ""
      push: "${paths.external}"
